name: Excavator

on:
  workflow_dispatch:
  schedule:
    # run at 5 11 17 24 hours
    - cron: "0 5,11,17,23 * * ?"

jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@main
      - name: Config git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git remote 'set-url' --push origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
      - name: Excavate check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          ./check.ps1
